### ISSUE TITLE
AttributeError: module 'tensorflow._api.v2.train' has no attribute 'Optimizer'

### ISSUE THREAD

**Issue by bhargavak1409** [xiangyue9607/CliniRC#2]
Error when I tried to run the code as per given instructions

Code:
!CUDA_VISIBLE_DEVICES=0 python ./BERT/run_squad.py \
    --vocab_file=./pretrained_bert_models/clinicalbert/vocab.txt \
    --bert_config_file=./pretrained_bert_models/clinicalbert/bert_config.json \
    --init_checkpoint=./pretrained_bert_models/clinicalbert/model.ckpt-100000 \
    --do_train=True \
    --train_file=./data/datasets/relation-train-sampled-0.05.json \
    --do_predict=True \
    --do_lower_case=False \
    --predict_file=./data/datasets/relation-dev.json \
    --train_batch_size=6 \
    --learning_rate=3e-5 \
    --num_train_epochs=4.0 \
    --max_seq_length=384 \
    --doc_stride=128 \
    --output_dir=./output/bert_models/clinicalbert_relation_0.05/

Error:
Traceback (most recent call last):
  File "./BERT/run_squad.py", line 28, in <module>
    import optimization
  File "/content/CliniRC/BERT/optimization.py", line 88, in <module>
    class AdamWeightDecayOptimizer(tf.train.Optimizer):
AttributeError: module 'tensorflow._api.v2.train' has no attribute 'Optimizer'

**Comment by xiangyue9607** [comment]
Hi!
I think it might be caused by the TensorFlow version. See a similar discussion here:

#https://github.com/google-research/bert/issues/934

**Comment by bhargavak1409** [comment]
> Hi!
> I think it might be caused by the TensorFlow version. See a similar discussion here:
> 
> #[google-research/bert#934](https://github.com/google-research/bert/issues/934)

Thanks for the reply. It will be really helpful if you mention the required TensorFlow, Python and CUDA version etc as well
